version: '3.8'

services:
  web:
    build: ./src
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    command: flask run --host=0.0.0.0
